from pathlib import Path
import json, os, platform, subprocess
before=json.loads(Path('/tmp/wt-baseline.json').read_text())
after=json.loads(Path('/tmp/wt-patched.json').read_text())
lines=['# Shared-query runtime performance','', '## Changes','', 'Source files, match/capture text, and cached JSX attribute payloads use immutable shared storage. Text values lazily cache their content digest; query lookups reuse it instead of hashing the same bytes for every rule. Matching spans still address the original UTF-8 bytes. Each consumer retains independent handles, scope, diagnostics, and logical budgets.','', '`SourceFile.text` is now `SharedText`; Rust callers construct it with `text: value.into()`. The CLI, JSON wire format and WT rule language are unchanged. `cache_key_bytes_hashed` reports physical hashing in native query-key construction separately from reader `bytes_hashed`.','', '## Measured comparison','', 'Baseline: `0819df83a49dfd99f76229aa59acde2f277b721d`. Both versions were measured sequentially in the same GitHub Actions job using Rust 1.94.0, release mode, 32 files and 128 consumer programs. Values below are medians of three fresh-snapshot runs. Persistent caches are not involved.','', '| Workload | Baseline (s) | Patched (s) | Baseline / patched |','|---|---:|---:|---:|']
for a,b in zip(before,after):
    assert a['workload']==b['workload']
    lines.append(f"| {a['workload']} | {a['median_seconds']:.6f} | {b['median_seconds']:.6f} | {a['median_seconds']/b['median_seconds']:.2f}x |")
lines+=['','These are isolated query-runtime measurements, not end-to-end `wt check` throughput. Compilation, file construction, disk enumeration, worker IPC and persistent-cache operations are outside the timed region. Shared-runner noise and small sample counts limit generalization. No timing threshold is asserted by tests. Result-vector traversal and independent predicate evaluation remain proportional to consumer/match counts.','', 'Reproduce with:','', '```sh','cargo test -p wt-runtime --release --locked --test shared_query_performance -- --ignored --nocapture','```','', 'The new regression tests cover once-per-snapshot hashing, content replacement at the same path/length, shared capture/JSX payloads, Unicode views, per-consumer file-index isolation, and optimized/reference findings and logical budgets.','', '## Measurement evidence','', f"Workflow run: {os.environ.get('GITHUB_SERVER_URL')}/{os.environ.get('GITHUB_REPOSITORY')}/actions/runs/{os.environ.get('GITHUB_RUN_ID')}", '', '```json',json.dumps({'baseline':before,'patched':after},indent=2),'```','']
Path('docs/shared-query-performance.md').write_text('\n'.join(lines))
